// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: configupdateresult.proto

package org.xgvela.oam.configupdateresult;

public interface CfgResultNotifyReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:configupdateresult.CfgResultNotifyReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string NfType = 1;</code>
   */
  String getNfType();
  /**
   * <code>string NfType = 1;</code>
   */
  com.google.protobuf.ByteString
      getNfTypeBytes();

  /**
   * <code>string InstanceId = 2;</code>
   */
  String getInstanceId();
  /**
   * <code>string InstanceId = 2;</code>
   */
  com.google.protobuf.ByteString
      getInstanceIdBytes();

  /**
   * <code>string TaskId = 3;</code>
   */
  String getTaskId();
  /**
   * <code>string TaskId = 3;</code>
   */
  com.google.protobuf.ByteString
      getTaskIdBytes();
}
