// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: configupdateresult.proto

package org.xgvela.oam.configupdateresult;

/**
 * Protobuf type {@code configupdateresult.CfgResultNotifyReq}
 */
public  final class CfgResultNotifyReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:configupdateresult.CfgResultNotifyReq)
    CfgResultNotifyReqOrBuilder {
  // Use CfgResultNotifyReq.newBuilder() to construct.
  private CfgResultNotifyReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CfgResultNotifyReq() {
    nfType_ = "";
    instanceId_ = "";
    msgId_ = 0;
    result_ = "";
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private CfgResultNotifyReq(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            String s = input.readStringRequireUtf8();

            nfType_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            instanceId_ = s;
            break;
          }
          case 24: {

            msgId_ = input.readUInt32();
            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();

            result_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ConfigUpdateResult.internal_static_configupdateresult_CfgResultNotifyReq_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ConfigUpdateResult.internal_static_configupdateresult_CfgResultNotifyReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            CfgResultNotifyReq.class, Builder.class);
  }

  public static final int NFTYPE_FIELD_NUMBER = 1;
  private volatile Object nfType_;
  /**
   * <code>string NfType = 1;</code>
   */
  public String getNfType() {
    Object ref = nfType_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      nfType_ = s;
      return s;
    }
  }
  /**
   * <code>string NfType = 1;</code>
   */
  public com.google.protobuf.ByteString
      getNfTypeBytes() {
    Object ref = nfType_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      nfType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INSTANCEID_FIELD_NUMBER = 2;
  private volatile Object instanceId_;
  /**
   * <code>string InstanceId = 2;</code>
   */
  public String getInstanceId() {
    Object ref = instanceId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      instanceId_ = s;
      return s;
    }
  }
  /**
   * <code>string InstanceId = 2;</code>
   */
  public com.google.protobuf.ByteString
      getInstanceIdBytes() {
    Object ref = instanceId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      instanceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MSGID_FIELD_NUMBER = 3;
  private int msgId_;
  /**
   * <code>uint32 MsgId = 3;</code>
   */
  public int getMsgId() {
    return msgId_;
  }

  public static final int RESULT_FIELD_NUMBER = 4;
  private volatile Object result_;
  /**
   * <code>string Result = 4;</code>
   */
  public String getResult() {
    Object ref = result_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      result_ = s;
      return s;
    }
  }
  /**
   * <code>string Result = 4;</code>
   */
  public com.google.protobuf.ByteString
      getResultBytes() {
    Object ref = result_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      result_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getNfTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, nfType_);
    }
    if (!getInstanceIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, instanceId_);
    }
    if (msgId_ != 0) {
      output.writeUInt32(3, msgId_);
    }
    if (!getResultBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, result_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNfTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, nfType_);
    }
    if (!getInstanceIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, instanceId_);
    }
    if (msgId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, msgId_);
    }
    if (!getResultBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, result_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof CfgResultNotifyReq)) {
      return super.equals(obj);
    }
    CfgResultNotifyReq other = (CfgResultNotifyReq) obj;

    boolean result = true;
    result = result && getNfType()
        .equals(other.getNfType());
    result = result && getInstanceId()
        .equals(other.getInstanceId());
    result = result && (getMsgId()
        == other.getMsgId());
    result = result && getResult()
        .equals(other.getResult());
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NFTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getNfType().hashCode();
    hash = (37 * hash) + INSTANCEID_FIELD_NUMBER;
    hash = (53 * hash) + getInstanceId().hashCode();
    hash = (37 * hash) + MSGID_FIELD_NUMBER;
    hash = (53 * hash) + getMsgId();
    hash = (37 * hash) + RESULT_FIELD_NUMBER;
    hash = (53 * hash) + getResult().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static CfgResultNotifyReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CfgResultNotifyReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CfgResultNotifyReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CfgResultNotifyReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CfgResultNotifyReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CfgResultNotifyReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CfgResultNotifyReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static CfgResultNotifyReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static CfgResultNotifyReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static CfgResultNotifyReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static CfgResultNotifyReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static CfgResultNotifyReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(CfgResultNotifyReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code configupdateresult.CfgResultNotifyReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:configupdateresult.CfgResultNotifyReq)
      CfgResultNotifyReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ConfigUpdateResult.internal_static_configupdateresult_CfgResultNotifyReq_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ConfigUpdateResult.internal_static_configupdateresult_CfgResultNotifyReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CfgResultNotifyReq.class, Builder.class);
    }

    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      nfType_ = "";

      instanceId_ = "";

      msgId_ = 0;

      result_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ConfigUpdateResult.internal_static_configupdateresult_CfgResultNotifyReq_descriptor;
    }

    public CfgResultNotifyReq getDefaultInstanceForType() {
      return CfgResultNotifyReq.getDefaultInstance();
    }

    public CfgResultNotifyReq build() {
      CfgResultNotifyReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public CfgResultNotifyReq buildPartial() {
      CfgResultNotifyReq result = new CfgResultNotifyReq(this);
      result.nfType_ = nfType_;
      result.instanceId_ = instanceId_;
      result.msgId_ = msgId_;
      result.result_ = result_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof CfgResultNotifyReq) {
        return mergeFrom((CfgResultNotifyReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(CfgResultNotifyReq other) {
      if (other == CfgResultNotifyReq.getDefaultInstance()) return this;
      if (!other.getNfType().isEmpty()) {
        nfType_ = other.nfType_;
        onChanged();
      }
      if (!other.getInstanceId().isEmpty()) {
        instanceId_ = other.instanceId_;
        onChanged();
      }
      if (other.getMsgId() != 0) {
        setMsgId(other.getMsgId());
      }
      if (!other.getResult().isEmpty()) {
        result_ = other.result_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      CfgResultNotifyReq parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (CfgResultNotifyReq) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object nfType_ = "";
    /**
     * <code>string NfType = 1;</code>
     */
    public String getNfType() {
      Object ref = nfType_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        nfType_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string NfType = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNfTypeBytes() {
      Object ref = nfType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        nfType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string NfType = 1;</code>
     */
    public Builder setNfType(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nfType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string NfType = 1;</code>
     */
    public Builder clearNfType() {
      
      nfType_ = getDefaultInstance().getNfType();
      onChanged();
      return this;
    }
    /**
     * <code>string NfType = 1;</code>
     */
    public Builder setNfTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nfType_ = value;
      onChanged();
      return this;
    }

    private Object instanceId_ = "";
    /**
     * <code>string InstanceId = 2;</code>
     */
    public String getInstanceId() {
      Object ref = instanceId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        instanceId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string InstanceId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getInstanceIdBytes() {
      Object ref = instanceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        instanceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string InstanceId = 2;</code>
     */
    public Builder setInstanceId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      instanceId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string InstanceId = 2;</code>
     */
    public Builder clearInstanceId() {
      
      instanceId_ = getDefaultInstance().getInstanceId();
      onChanged();
      return this;
    }
    /**
     * <code>string InstanceId = 2;</code>
     */
    public Builder setInstanceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      instanceId_ = value;
      onChanged();
      return this;
    }

    private int msgId_ ;
    /**
     * <code>uint32 MsgId = 3;</code>
     */
    public int getMsgId() {
      return msgId_;
    }
    /**
     * <code>uint32 MsgId = 3;</code>
     */
    public Builder setMsgId(int value) {
      
      msgId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 MsgId = 3;</code>
     */
    public Builder clearMsgId() {
      
      msgId_ = 0;
      onChanged();
      return this;
    }

    private Object result_ = "";
    /**
     * <code>string Result = 4;</code>
     */
    public String getResult() {
      Object ref = result_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        result_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string Result = 4;</code>
     */
    public com.google.protobuf.ByteString
        getResultBytes() {
      Object ref = result_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        result_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string Result = 4;</code>
     */
    public Builder setResult(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      result_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string Result = 4;</code>
     */
    public Builder clearResult() {
      
      result_ = getDefaultInstance().getResult();
      onChanged();
      return this;
    }
    /**
     * <code>string Result = 4;</code>
     */
    public Builder setResultBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      result_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:configupdateresult.CfgResultNotifyReq)
  }

  // @@protoc_insertion_point(class_scope:configupdateresult.CfgResultNotifyReq)
  private static final CfgResultNotifyReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new CfgResultNotifyReq();
  }

  public static CfgResultNotifyReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CfgResultNotifyReq>
      PARSER = new com.google.protobuf.AbstractParser<CfgResultNotifyReq>() {
    public CfgResultNotifyReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new CfgResultNotifyReq(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CfgResultNotifyReq> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<CfgResultNotifyReq> getParserForType() {
    return PARSER;
  }

  public CfgResultNotifyReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

