// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: configupdateresult.proto

package org.xgvela.oam.configupdateresult;

public interface CfgResultNotifyRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:configupdateresult.CfgResultNotifyResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 0 succ 1 failed 2 need reboot
   * </pre>
   *
   * <code>string Result = 1;</code>
   */
  String getResult();
  /**
   * <pre>
   * 0 succ 1 failed 2 need reboot
   * </pre>
   *
   * <code>string Result = 1;</code>
   */
  com.google.protobuf.ByteString
      getResultBytes();
}
