// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: configupdateresult.proto

package org.xgvela.oam.configupdateresult;

public final class ConfigUpdateResult {
  private ConfigUpdateResult() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_configupdateresult_CfgResultNotifyReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_configupdateresult_CfgResultNotifyReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_configupdateresult_CfgResultNotifyResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_configupdateresult_CfgResultNotifyResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\030configupdateresult.proto\022\022configupdate" +
      "result\"H\n\022CfgResultNotifyReq\022\016\n\006NfType\030\001" +
      " \001(\t\022\022\n\nInstanceId\030\002 \001(\t\022\016\n\006TaskId\030\003 \001(\t" +
      "\"%\n\023CfgResultNotifyResp\022\016\n\006Result\030\001 \001(\t2" +
      "\201\001\n\031ConfigUpdateResultService\022d\n\017cfgUpda" +
      "teResult\022&.configupdateresult.CfgResultN" +
      "otifyReq\032\'.configupdateresult.CfgResultN" +
      "otifyResp\"\000B?\n!org.xgvela.oam.configupda" +
      "teresultB\022ConfigUpdateResultP\001\242\002\003CRNb\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_configupdateresult_CfgResultNotifyReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_configupdateresult_CfgResultNotifyReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_configupdateresult_CfgResultNotifyReq_descriptor,
        new String[] { "NfType", "InstanceId", "TaskId", });
    internal_static_configupdateresult_CfgResultNotifyResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_configupdateresult_CfgResultNotifyResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_configupdateresult_CfgResultNotifyResp_descriptor,
        new String[] { "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
