// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nftask.proto

package org.xgvela.oam.nftask;

public interface NfTaskReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nftask.NfTaskReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 taskId = 1;</code>
   */
  int getTaskId();

  /**
   * <code>string dataType = 2;</code>
   */
  String getDataType();
  /**
   * <code>string dataType = 2;</code>
   */
  com.google.protobuf.ByteString
      getDataTypeBytes();

  /**
   * <code>string userNumber = 3;</code>
   */
  String getUserNumber();
  /**
   * <code>string userNumber = 3;</code>
   */
  com.google.protobuf.ByteString
      getUserNumberBytes();

  /**
   * <code>uint32 runNow = 4;</code>
   */
  int getRunNow();

  /**
   * <code>uint32 timeLength = 5;</code>
   */
  int getTimeLength();

  /**
   * <code>uint64 startTime = 6;</code>
   */
  long getStartTime();

  /**
   * <code>uint64 endTime = 7;</code>
   */
  long getEndTime();

  /**
   * <code>uint32 status = 8;</code>
   */
  int getStatus();

  /**
   * <code>repeated string interfaceType = 9;</code>
   */
  java.util.List<String>
      getInterfaceTypeList();
  /**
   * <code>repeated string interfaceType = 9;</code>
   */
  int getInterfaceTypeCount();
  /**
   * <code>repeated string interfaceType = 9;</code>
   */
  String getInterfaceType(int index);
  /**
   * <code>repeated string interfaceType = 9;</code>
   */
  com.google.protobuf.ByteString
      getInterfaceTypeBytes(int index);
}
