// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nftask.proto

package org.xgvela.oam.nftask;

public interface NfTaskReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nftask.NfTaskReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 taskId = 1;</code>
   */
  int getTaskId();

  /**
   * <code>string neId = 2;</code>
   */
  String getNeId();
  /**
   * <code>string neId = 2;</code>
   */
  com.google.protobuf.ByteString
      getNeIdBytes();

  /**
   * <code>string nfType = 3;</code>
   */
  String getNfType();
  /**
   * <code>string nfType = 3;</code>
   */
  com.google.protobuf.ByteString
      getNfTypeBytes();

  /**
   * <code>string dataType = 4;</code>
   */
  String getDataType();
  /**
   * <code>string dataType = 4;</code>
   */
  com.google.protobuf.ByteString
      getDataTypeBytes();

  /**
   * <code>string userNumber = 5;</code>
   */
  String getUserNumber();
  /**
   * <code>string userNumber = 5;</code>
   */
  com.google.protobuf.ByteString
      getUserNumberBytes();

  /**
   * <code>bool runNow = 6;</code>
   */
  boolean getRunNow();

  /**
   * <code>double timeLength = 7;</code>
   */
  double getTimeLength();

  /**
   * <code>uint64 startTime = 8;</code>
   */
  long getStartTime();

  /**
   * <code>uint64 endTime = 9;</code>
   */
  long getEndTime();

  /**
   * <code>uint32 status = 10;</code>
   */
  int getStatus();

  /**
   * <code>string interfaceType = 11;</code>
   */
  String getInterfaceType();
  /**
   * <code>string interfaceType = 11;</code>
   */
  com.google.protobuf.ByteString
      getInterfaceTypeBytes();
}
