// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nftask.proto

package org.xgvela.oam.nftask;

/**
 * Protobuf type {@code nftask.NfTaskReq}
 */
public  final class NfTaskReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:nftask.NfTaskReq)
    NfTaskReqOrBuilder {
  // Use NfTaskReq.newBuilder() to construct.
  private NfTaskReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NfTaskReq() {
    taskId_ = 0;
    dataType_ = "";
    userNumber_ = "";
    runNow_ = 0;
    timeLength_ = 0;
    startTime_ = 0L;
    endTime_ = 0L;
    status_ = 0;
    interfaceType_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private NfTaskReq(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            taskId_ = input.readUInt32();
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            dataType_ = s;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            userNumber_ = s;
            break;
          }
          case 32: {

            runNow_ = input.readUInt32();
            break;
          }
          case 40: {

            timeLength_ = input.readUInt32();
            break;
          }
          case 48: {

            startTime_ = input.readUInt64();
            break;
          }
          case 56: {

            endTime_ = input.readUInt64();
            break;
          }
          case 64: {

            status_ = input.readUInt32();
            break;
          }
          case 74: {
            String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
              interfaceType_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000100;
            }
            interfaceType_.add(s);
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
        interfaceType_ = interfaceType_.getUnmodifiableView();
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return NFTask.internal_static_nftask_NfTaskReq_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return NFTask.internal_static_nftask_NfTaskReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            NfTaskReq.class, Builder.class);
  }

  private int bitField0_;
  public static final int TASKID_FIELD_NUMBER = 1;
  private int taskId_;
  /**
   * <code>uint32 taskId = 1;</code>
   */
  public int getTaskId() {
    return taskId_;
  }

  public static final int DATATYPE_FIELD_NUMBER = 2;
  private volatile Object dataType_;
  /**
   * <code>string dataType = 2;</code>
   */
  public String getDataType() {
    Object ref = dataType_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      dataType_ = s;
      return s;
    }
  }
  /**
   * <code>string dataType = 2;</code>
   */
  public com.google.protobuf.ByteString
      getDataTypeBytes() {
    Object ref = dataType_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      dataType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERNUMBER_FIELD_NUMBER = 3;
  private volatile Object userNumber_;
  /**
   * <code>string userNumber = 3;</code>
   */
  public String getUserNumber() {
    Object ref = userNumber_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      userNumber_ = s;
      return s;
    }
  }
  /**
   * <code>string userNumber = 3;</code>
   */
  public com.google.protobuf.ByteString
      getUserNumberBytes() {
    Object ref = userNumber_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      userNumber_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RUNNOW_FIELD_NUMBER = 4;
  private int runNow_;
  /**
   * <code>uint32 runNow = 4;</code>
   */
  public int getRunNow() {
    return runNow_;
  }

  public static final int TIMELENGTH_FIELD_NUMBER = 5;
  private int timeLength_;
  /**
   * <code>uint32 timeLength = 5;</code>
   */
  public int getTimeLength() {
    return timeLength_;
  }

  public static final int STARTTIME_FIELD_NUMBER = 6;
  private long startTime_;
  /**
   * <code>uint64 startTime = 6;</code>
   */
  public long getStartTime() {
    return startTime_;
  }

  public static final int ENDTIME_FIELD_NUMBER = 7;
  private long endTime_;
  /**
   * <code>uint64 endTime = 7;</code>
   */
  public long getEndTime() {
    return endTime_;
  }

  public static final int STATUS_FIELD_NUMBER = 8;
  private int status_;
  /**
   * <code>uint32 status = 8;</code>
   */
  public int getStatus() {
    return status_;
  }

  public static final int INTERFACETYPE_FIELD_NUMBER = 9;
  private com.google.protobuf.LazyStringList interfaceType_;
  /**
   * <code>repeated string interfaceType = 9;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getInterfaceTypeList() {
    return interfaceType_;
  }
  /**
   * <code>repeated string interfaceType = 9;</code>
   */
  public int getInterfaceTypeCount() {
    return interfaceType_.size();
  }
  /**
   * <code>repeated string interfaceType = 9;</code>
   */
  public String getInterfaceType(int index) {
    return interfaceType_.get(index);
  }
  /**
   * <code>repeated string interfaceType = 9;</code>
   */
  public com.google.protobuf.ByteString
      getInterfaceTypeBytes(int index) {
    return interfaceType_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (taskId_ != 0) {
      output.writeUInt32(1, taskId_);
    }
    if (!getDataTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, dataType_);
    }
    if (!getUserNumberBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, userNumber_);
    }
    if (runNow_ != 0) {
      output.writeUInt32(4, runNow_);
    }
    if (timeLength_ != 0) {
      output.writeUInt32(5, timeLength_);
    }
    if (startTime_ != 0L) {
      output.writeUInt64(6, startTime_);
    }
    if (endTime_ != 0L) {
      output.writeUInt64(7, endTime_);
    }
    if (status_ != 0) {
      output.writeUInt32(8, status_);
    }
    for (int i = 0; i < interfaceType_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, interfaceType_.getRaw(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (taskId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, taskId_);
    }
    if (!getDataTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, dataType_);
    }
    if (!getUserNumberBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, userNumber_);
    }
    if (runNow_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, runNow_);
    }
    if (timeLength_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(5, timeLength_);
    }
    if (startTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(6, startTime_);
    }
    if (endTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(7, endTime_);
    }
    if (status_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(8, status_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < interfaceType_.size(); i++) {
        dataSize += computeStringSizeNoTag(interfaceType_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getInterfaceTypeList().size();
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof NfTaskReq)) {
      return super.equals(obj);
    }
    NfTaskReq other = (NfTaskReq) obj;

    boolean result = true;
    result = result && (getTaskId()
        == other.getTaskId());
    result = result && getDataType()
        .equals(other.getDataType());
    result = result && getUserNumber()
        .equals(other.getUserNumber());
    result = result && (getRunNow()
        == other.getRunNow());
    result = result && (getTimeLength()
        == other.getTimeLength());
    result = result && (getStartTime()
        == other.getStartTime());
    result = result && (getEndTime()
        == other.getEndTime());
    result = result && (getStatus()
        == other.getStatus());
    result = result && getInterfaceTypeList()
        .equals(other.getInterfaceTypeList());
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TASKID_FIELD_NUMBER;
    hash = (53 * hash) + getTaskId();
    hash = (37 * hash) + DATATYPE_FIELD_NUMBER;
    hash = (53 * hash) + getDataType().hashCode();
    hash = (37 * hash) + USERNUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getUserNumber().hashCode();
    hash = (37 * hash) + RUNNOW_FIELD_NUMBER;
    hash = (53 * hash) + getRunNow();
    hash = (37 * hash) + TIMELENGTH_FIELD_NUMBER;
    hash = (53 * hash) + getTimeLength();
    hash = (37 * hash) + STARTTIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getStartTime());
    hash = (37 * hash) + ENDTIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getEndTime());
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus();
    if (getInterfaceTypeCount() > 0) {
      hash = (37 * hash) + INTERFACETYPE_FIELD_NUMBER;
      hash = (53 * hash) + getInterfaceTypeList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static NfTaskReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static NfTaskReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static NfTaskReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static NfTaskReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static NfTaskReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static NfTaskReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static NfTaskReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static NfTaskReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static NfTaskReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static NfTaskReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static NfTaskReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static NfTaskReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(NfTaskReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code nftask.NfTaskReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:nftask.NfTaskReq)
      NfTaskReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return NFTask.internal_static_nftask_NfTaskReq_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return NFTask.internal_static_nftask_NfTaskReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              NfTaskReq.class, Builder.class);
    }

    // Construct using NfTaskReq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      taskId_ = 0;

      dataType_ = "";

      userNumber_ = "";

      runNow_ = 0;

      timeLength_ = 0;

      startTime_ = 0L;

      endTime_ = 0L;

      status_ = 0;

      interfaceType_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000100);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return NFTask.internal_static_nftask_NfTaskReq_descriptor;
    }

    public NfTaskReq getDefaultInstanceForType() {
      return NfTaskReq.getDefaultInstance();
    }

    public NfTaskReq build() {
      NfTaskReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public NfTaskReq buildPartial() {
      NfTaskReq result = new NfTaskReq(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.taskId_ = taskId_;
      result.dataType_ = dataType_;
      result.userNumber_ = userNumber_;
      result.runNow_ = runNow_;
      result.timeLength_ = timeLength_;
      result.startTime_ = startTime_;
      result.endTime_ = endTime_;
      result.status_ = status_;
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        interfaceType_ = interfaceType_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000100);
      }
      result.interfaceType_ = interfaceType_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof NfTaskReq) {
        return mergeFrom((NfTaskReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(NfTaskReq other) {
      if (other == NfTaskReq.getDefaultInstance()) return this;
      if (other.getTaskId() != 0) {
        setTaskId(other.getTaskId());
      }
      if (!other.getDataType().isEmpty()) {
        dataType_ = other.dataType_;
        onChanged();
      }
      if (!other.getUserNumber().isEmpty()) {
        userNumber_ = other.userNumber_;
        onChanged();
      }
      if (other.getRunNow() != 0) {
        setRunNow(other.getRunNow());
      }
      if (other.getTimeLength() != 0) {
        setTimeLength(other.getTimeLength());
      }
      if (other.getStartTime() != 0L) {
        setStartTime(other.getStartTime());
      }
      if (other.getEndTime() != 0L) {
        setEndTime(other.getEndTime());
      }
      if (other.getStatus() != 0) {
        setStatus(other.getStatus());
      }
      if (!other.interfaceType_.isEmpty()) {
        if (interfaceType_.isEmpty()) {
          interfaceType_ = other.interfaceType_;
          bitField0_ = (bitField0_ & ~0x00000100);
        } else {
          ensureInterfaceTypeIsMutable();
          interfaceType_.addAll(other.interfaceType_);
        }
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      NfTaskReq parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (NfTaskReq) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int taskId_ ;
    /**
     * <code>uint32 taskId = 1;</code>
     */
    public int getTaskId() {
      return taskId_;
    }
    /**
     * <code>uint32 taskId = 1;</code>
     */
    public Builder setTaskId(int value) {
      
      taskId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 taskId = 1;</code>
     */
    public Builder clearTaskId() {
      
      taskId_ = 0;
      onChanged();
      return this;
    }

    private Object dataType_ = "";
    /**
     * <code>string dataType = 2;</code>
     */
    public String getDataType() {
      Object ref = dataType_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        dataType_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string dataType = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDataTypeBytes() {
      Object ref = dataType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        dataType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string dataType = 2;</code>
     */
    public Builder setDataType(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dataType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string dataType = 2;</code>
     */
    public Builder clearDataType() {
      
      dataType_ = getDefaultInstance().getDataType();
      onChanged();
      return this;
    }
    /**
     * <code>string dataType = 2;</code>
     */
    public Builder setDataTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dataType_ = value;
      onChanged();
      return this;
    }

    private Object userNumber_ = "";
    /**
     * <code>string userNumber = 3;</code>
     */
    public String getUserNumber() {
      Object ref = userNumber_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        userNumber_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string userNumber = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUserNumberBytes() {
      Object ref = userNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        userNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string userNumber = 3;</code>
     */
    public Builder setUserNumber(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string userNumber = 3;</code>
     */
    public Builder clearUserNumber() {
      
      userNumber_ = getDefaultInstance().getUserNumber();
      onChanged();
      return this;
    }
    /**
     * <code>string userNumber = 3;</code>
     */
    public Builder setUserNumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userNumber_ = value;
      onChanged();
      return this;
    }

    private int runNow_ ;
    /**
     * <code>uint32 runNow = 4;</code>
     */
    public int getRunNow() {
      return runNow_;
    }
    /**
     * <code>uint32 runNow = 4;</code>
     */
    public Builder setRunNow(int value) {
      
      runNow_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 runNow = 4;</code>
     */
    public Builder clearRunNow() {
      
      runNow_ = 0;
      onChanged();
      return this;
    }

    private int timeLength_ ;
    /**
     * <code>uint32 timeLength = 5;</code>
     */
    public int getTimeLength() {
      return timeLength_;
    }
    /**
     * <code>uint32 timeLength = 5;</code>
     */
    public Builder setTimeLength(int value) {
      
      timeLength_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 timeLength = 5;</code>
     */
    public Builder clearTimeLength() {
      
      timeLength_ = 0;
      onChanged();
      return this;
    }

    private long startTime_ ;
    /**
     * <code>uint64 startTime = 6;</code>
     */
    public long getStartTime() {
      return startTime_;
    }
    /**
     * <code>uint64 startTime = 6;</code>
     */
    public Builder setStartTime(long value) {
      
      startTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 startTime = 6;</code>
     */
    public Builder clearStartTime() {
      
      startTime_ = 0L;
      onChanged();
      return this;
    }

    private long endTime_ ;
    /**
     * <code>uint64 endTime = 7;</code>
     */
    public long getEndTime() {
      return endTime_;
    }
    /**
     * <code>uint64 endTime = 7;</code>
     */
    public Builder setEndTime(long value) {
      
      endTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 endTime = 7;</code>
     */
    public Builder clearEndTime() {
      
      endTime_ = 0L;
      onChanged();
      return this;
    }

    private int status_ ;
    /**
     * <code>uint32 status = 8;</code>
     */
    public int getStatus() {
      return status_;
    }
    /**
     * <code>uint32 status = 8;</code>
     */
    public Builder setStatus(int value) {
      
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 status = 8;</code>
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList interfaceType_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureInterfaceTypeIsMutable() {
      if (!((bitField0_ & 0x00000100) == 0x00000100)) {
        interfaceType_ = new com.google.protobuf.LazyStringArrayList(interfaceType_);
        bitField0_ |= 0x00000100;
       }
    }
    /**
     * <code>repeated string interfaceType = 9;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getInterfaceTypeList() {
      return interfaceType_.getUnmodifiableView();
    }
    /**
     * <code>repeated string interfaceType = 9;</code>
     */
    public int getInterfaceTypeCount() {
      return interfaceType_.size();
    }
    /**
     * <code>repeated string interfaceType = 9;</code>
     */
    public String getInterfaceType(int index) {
      return interfaceType_.get(index);
    }
    /**
     * <code>repeated string interfaceType = 9;</code>
     */
    public com.google.protobuf.ByteString
        getInterfaceTypeBytes(int index) {
      return interfaceType_.getByteString(index);
    }
    /**
     * <code>repeated string interfaceType = 9;</code>
     */
    public Builder setInterfaceType(
        int index, String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureInterfaceTypeIsMutable();
      interfaceType_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string interfaceType = 9;</code>
     */
    public Builder addInterfaceType(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureInterfaceTypeIsMutable();
      interfaceType_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string interfaceType = 9;</code>
     */
    public Builder addAllInterfaceType(
        Iterable<String> values) {
      ensureInterfaceTypeIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, interfaceType_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string interfaceType = 9;</code>
     */
    public Builder clearInterfaceType() {
      interfaceType_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string interfaceType = 9;</code>
     */
    public Builder addInterfaceTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureInterfaceTypeIsMutable();
      interfaceType_.add(value);
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:nftask.NfTaskReq)
  }

  // @@protoc_insertion_point(class_scope:nftask.NfTaskReq)
  private static final NfTaskReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new NfTaskReq();
  }

  public static NfTaskReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NfTaskReq>
      PARSER = new com.google.protobuf.AbstractParser<NfTaskReq>() {
    public NfTaskReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new NfTaskReq(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<NfTaskReq> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<NfTaskReq> getParserForType() {
    return PARSER;
  }

  public NfTaskReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

