// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nftask.proto

package org.xgvela.oam.nftask;

/**
 * Protobuf type {@code nftask.NfTaskReq}
 */
public  final class NfTaskReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:nftask.NfTaskReq)
    NfTaskReqOrBuilder {
  // Use NfTaskReq.newBuilder() to construct.
  private NfTaskReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NfTaskReq() {
    taskId_ = 0;
    neId_ = "";
    nfType_ = "";
    dataType_ = "";
    userNumber_ = "";
    runNow_ = false;
    timeLength_ = 0D;
    startTime_ = 0L;
    endTime_ = 0L;
    status_ = 0;
    interfaceType_ = "";
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private NfTaskReq(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            taskId_ = input.readUInt32();
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            neId_ = s;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            nfType_ = s;
            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();

            dataType_ = s;
            break;
          }
          case 42: {
            String s = input.readStringRequireUtf8();

            userNumber_ = s;
            break;
          }
          case 48: {

            runNow_ = input.readBool();
            break;
          }
          case 57: {

            timeLength_ = input.readDouble();
            break;
          }
          case 64: {

            startTime_ = input.readUInt64();
            break;
          }
          case 72: {

            endTime_ = input.readUInt64();
            break;
          }
          case 80: {

            status_ = input.readUInt32();
            break;
          }
          case 90: {
            String s = input.readStringRequireUtf8();

            interfaceType_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return NFTask.internal_static_nftask_NfTaskReq_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return NFTask.internal_static_nftask_NfTaskReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            NfTaskReq.class, Builder.class);
  }

  public static final int TASKID_FIELD_NUMBER = 1;
  private int taskId_;
  /**
   * <code>uint32 taskId = 1;</code>
   */
  public int getTaskId() {
    return taskId_;
  }

  public static final int NEID_FIELD_NUMBER = 2;
  private volatile Object neId_;
  /**
   * <code>string neId = 2;</code>
   */
  public String getNeId() {
    Object ref = neId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      neId_ = s;
      return s;
    }
  }
  /**
   * <code>string neId = 2;</code>
   */
  public com.google.protobuf.ByteString
      getNeIdBytes() {
    Object ref = neId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      neId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NFTYPE_FIELD_NUMBER = 3;
  private volatile Object nfType_;
  /**
   * <code>string nfType = 3;</code>
   */
  public String getNfType() {
    Object ref = nfType_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      nfType_ = s;
      return s;
    }
  }
  /**
   * <code>string nfType = 3;</code>
   */
  public com.google.protobuf.ByteString
      getNfTypeBytes() {
    Object ref = nfType_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      nfType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATATYPE_FIELD_NUMBER = 4;
  private volatile Object dataType_;
  /**
   * <code>string dataType = 4;</code>
   */
  public String getDataType() {
    Object ref = dataType_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      dataType_ = s;
      return s;
    }
  }
  /**
   * <code>string dataType = 4;</code>
   */
  public com.google.protobuf.ByteString
      getDataTypeBytes() {
    Object ref = dataType_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      dataType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERNUMBER_FIELD_NUMBER = 5;
  private volatile Object userNumber_;
  /**
   * <code>string userNumber = 5;</code>
   */
  public String getUserNumber() {
    Object ref = userNumber_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      userNumber_ = s;
      return s;
    }
  }
  /**
   * <code>string userNumber = 5;</code>
   */
  public com.google.protobuf.ByteString
      getUserNumberBytes() {
    Object ref = userNumber_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      userNumber_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RUNNOW_FIELD_NUMBER = 6;
  private boolean runNow_;
  /**
   * <code>bool runNow = 6;</code>
   */
  public boolean getRunNow() {
    return runNow_;
  }

  public static final int TIMELENGTH_FIELD_NUMBER = 7;
  private double timeLength_;
  /**
   * <code>double timeLength = 7;</code>
   */
  public double getTimeLength() {
    return timeLength_;
  }

  public static final int STARTTIME_FIELD_NUMBER = 8;
  private long startTime_;
  /**
   * <code>uint64 startTime = 8;</code>
   */
  public long getStartTime() {
    return startTime_;
  }

  public static final int ENDTIME_FIELD_NUMBER = 9;
  private long endTime_;
  /**
   * <code>uint64 endTime = 9;</code>
   */
  public long getEndTime() {
    return endTime_;
  }

  public static final int STATUS_FIELD_NUMBER = 10;
  private int status_;
  /**
   * <code>uint32 status = 10;</code>
   */
  public int getStatus() {
    return status_;
  }

  public static final int INTERFACETYPE_FIELD_NUMBER = 11;
  private volatile Object interfaceType_;
  /**
   * <code>string interfaceType = 11;</code>
   */
  public String getInterfaceType() {
    Object ref = interfaceType_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      interfaceType_ = s;
      return s;
    }
  }
  /**
   * <code>string interfaceType = 11;</code>
   */
  public com.google.protobuf.ByteString
      getInterfaceTypeBytes() {
    Object ref = interfaceType_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      interfaceType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (taskId_ != 0) {
      output.writeUInt32(1, taskId_);
    }
    if (!getNeIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, neId_);
    }
    if (!getNfTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, nfType_);
    }
    if (!getDataTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, dataType_);
    }
    if (!getUserNumberBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, userNumber_);
    }
    if (runNow_ != false) {
      output.writeBool(6, runNow_);
    }
    if (timeLength_ != 0D) {
      output.writeDouble(7, timeLength_);
    }
    if (startTime_ != 0L) {
      output.writeUInt64(8, startTime_);
    }
    if (endTime_ != 0L) {
      output.writeUInt64(9, endTime_);
    }
    if (status_ != 0) {
      output.writeUInt32(10, status_);
    }
    if (!getInterfaceTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, interfaceType_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (taskId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, taskId_);
    }
    if (!getNeIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, neId_);
    }
    if (!getNfTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, nfType_);
    }
    if (!getDataTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, dataType_);
    }
    if (!getUserNumberBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, userNumber_);
    }
    if (runNow_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, runNow_);
    }
    if (timeLength_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(7, timeLength_);
    }
    if (startTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(8, startTime_);
    }
    if (endTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(9, endTime_);
    }
    if (status_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(10, status_);
    }
    if (!getInterfaceTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, interfaceType_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof NfTaskReq)) {
      return super.equals(obj);
    }
    NfTaskReq other = (NfTaskReq) obj;

    boolean result = true;
    result = result && (getTaskId()
        == other.getTaskId());
    result = result && getNeId()
        .equals(other.getNeId());
    result = result && getNfType()
        .equals(other.getNfType());
    result = result && getDataType()
        .equals(other.getDataType());
    result = result && getUserNumber()
        .equals(other.getUserNumber());
    result = result && (getRunNow()
        == other.getRunNow());
    result = result && (
        Double.doubleToLongBits(getTimeLength())
        == Double.doubleToLongBits(
            other.getTimeLength()));
    result = result && (getStartTime()
        == other.getStartTime());
    result = result && (getEndTime()
        == other.getEndTime());
    result = result && (getStatus()
        == other.getStatus());
    result = result && getInterfaceType()
        .equals(other.getInterfaceType());
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TASKID_FIELD_NUMBER;
    hash = (53 * hash) + getTaskId();
    hash = (37 * hash) + NEID_FIELD_NUMBER;
    hash = (53 * hash) + getNeId().hashCode();
    hash = (37 * hash) + NFTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getNfType().hashCode();
    hash = (37 * hash) + DATATYPE_FIELD_NUMBER;
    hash = (53 * hash) + getDataType().hashCode();
    hash = (37 * hash) + USERNUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getUserNumber().hashCode();
    hash = (37 * hash) + RUNNOW_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getRunNow());
    hash = (37 * hash) + TIMELENGTH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        Double.doubleToLongBits(getTimeLength()));
    hash = (37 * hash) + STARTTIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getStartTime());
    hash = (37 * hash) + ENDTIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getEndTime());
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus();
    hash = (37 * hash) + INTERFACETYPE_FIELD_NUMBER;
    hash = (53 * hash) + getInterfaceType().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static NfTaskReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static NfTaskReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static NfTaskReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static NfTaskReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static NfTaskReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static NfTaskReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static NfTaskReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static NfTaskReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static NfTaskReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static NfTaskReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static NfTaskReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static NfTaskReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(NfTaskReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code nftask.NfTaskReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:nftask.NfTaskReq)
      NfTaskReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return NFTask.internal_static_nftask_NfTaskReq_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return NFTask.internal_static_nftask_NfTaskReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              NfTaskReq.class, Builder.class);
    }

    // Construct using org.xgvela.oam.nftask.NfTaskReq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      taskId_ = 0;

      neId_ = "";

      nfType_ = "";

      dataType_ = "";

      userNumber_ = "";

      runNow_ = false;

      timeLength_ = 0D;

      startTime_ = 0L;

      endTime_ = 0L;

      status_ = 0;

      interfaceType_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return NFTask.internal_static_nftask_NfTaskReq_descriptor;
    }

    public NfTaskReq getDefaultInstanceForType() {
      return NfTaskReq.getDefaultInstance();
    }

    public NfTaskReq build() {
      NfTaskReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public NfTaskReq buildPartial() {
      NfTaskReq result = new NfTaskReq(this);
      result.taskId_ = taskId_;
      result.neId_ = neId_;
      result.nfType_ = nfType_;
      result.dataType_ = dataType_;
      result.userNumber_ = userNumber_;
      result.runNow_ = runNow_;
      result.timeLength_ = timeLength_;
      result.startTime_ = startTime_;
      result.endTime_ = endTime_;
      result.status_ = status_;
      result.interfaceType_ = interfaceType_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof NfTaskReq) {
        return mergeFrom((NfTaskReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(NfTaskReq other) {
      if (other == NfTaskReq.getDefaultInstance()) return this;
      if (other.getTaskId() != 0) {
        setTaskId(other.getTaskId());
      }
      if (!other.getNeId().isEmpty()) {
        neId_ = other.neId_;
        onChanged();
      }
      if (!other.getNfType().isEmpty()) {
        nfType_ = other.nfType_;
        onChanged();
      }
      if (!other.getDataType().isEmpty()) {
        dataType_ = other.dataType_;
        onChanged();
      }
      if (!other.getUserNumber().isEmpty()) {
        userNumber_ = other.userNumber_;
        onChanged();
      }
      if (other.getRunNow() != false) {
        setRunNow(other.getRunNow());
      }
      if (other.getTimeLength() != 0D) {
        setTimeLength(other.getTimeLength());
      }
      if (other.getStartTime() != 0L) {
        setStartTime(other.getStartTime());
      }
      if (other.getEndTime() != 0L) {
        setEndTime(other.getEndTime());
      }
      if (other.getStatus() != 0) {
        setStatus(other.getStatus());
      }
      if (!other.getInterfaceType().isEmpty()) {
        interfaceType_ = other.interfaceType_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      NfTaskReq parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (NfTaskReq) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int taskId_ ;
    /**
     * <code>uint32 taskId = 1;</code>
     */
    public int getTaskId() {
      return taskId_;
    }
    /**
     * <code>uint32 taskId = 1;</code>
     */
    public Builder setTaskId(int value) {
      
      taskId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 taskId = 1;</code>
     */
    public Builder clearTaskId() {
      
      taskId_ = 0;
      onChanged();
      return this;
    }

    private Object neId_ = "";
    /**
     * <code>string neId = 2;</code>
     */
    public String getNeId() {
      Object ref = neId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        neId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string neId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNeIdBytes() {
      Object ref = neId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        neId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string neId = 2;</code>
     */
    public Builder setNeId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      neId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string neId = 2;</code>
     */
    public Builder clearNeId() {
      
      neId_ = getDefaultInstance().getNeId();
      onChanged();
      return this;
    }
    /**
     * <code>string neId = 2;</code>
     */
    public Builder setNeIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      neId_ = value;
      onChanged();
      return this;
    }

    private Object nfType_ = "";
    /**
     * <code>string nfType = 3;</code>
     */
    public String getNfType() {
      Object ref = nfType_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        nfType_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string nfType = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNfTypeBytes() {
      Object ref = nfType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        nfType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string nfType = 3;</code>
     */
    public Builder setNfType(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nfType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string nfType = 3;</code>
     */
    public Builder clearNfType() {
      
      nfType_ = getDefaultInstance().getNfType();
      onChanged();
      return this;
    }
    /**
     * <code>string nfType = 3;</code>
     */
    public Builder setNfTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nfType_ = value;
      onChanged();
      return this;
    }

    private Object dataType_ = "";
    /**
     * <code>string dataType = 4;</code>
     */
    public String getDataType() {
      Object ref = dataType_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        dataType_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string dataType = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDataTypeBytes() {
      Object ref = dataType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        dataType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string dataType = 4;</code>
     */
    public Builder setDataType(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dataType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string dataType = 4;</code>
     */
    public Builder clearDataType() {
      
      dataType_ = getDefaultInstance().getDataType();
      onChanged();
      return this;
    }
    /**
     * <code>string dataType = 4;</code>
     */
    public Builder setDataTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dataType_ = value;
      onChanged();
      return this;
    }

    private Object userNumber_ = "";
    /**
     * <code>string userNumber = 5;</code>
     */
    public String getUserNumber() {
      Object ref = userNumber_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        userNumber_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string userNumber = 5;</code>
     */
    public com.google.protobuf.ByteString
        getUserNumberBytes() {
      Object ref = userNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        userNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string userNumber = 5;</code>
     */
    public Builder setUserNumber(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string userNumber = 5;</code>
     */
    public Builder clearUserNumber() {
      
      userNumber_ = getDefaultInstance().getUserNumber();
      onChanged();
      return this;
    }
    /**
     * <code>string userNumber = 5;</code>
     */
    public Builder setUserNumberBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userNumber_ = value;
      onChanged();
      return this;
    }

    private boolean runNow_ ;
    /**
     * <code>bool runNow = 6;</code>
     */
    public boolean getRunNow() {
      return runNow_;
    }
    /**
     * <code>bool runNow = 6;</code>
     */
    public Builder setRunNow(boolean value) {
      
      runNow_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool runNow = 6;</code>
     */
    public Builder clearRunNow() {
      
      runNow_ = false;
      onChanged();
      return this;
    }

    private double timeLength_ ;
    /**
     * <code>double timeLength = 7;</code>
     */
    public double getTimeLength() {
      return timeLength_;
    }
    /**
     * <code>double timeLength = 7;</code>
     */
    public Builder setTimeLength(double value) {
      
      timeLength_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double timeLength = 7;</code>
     */
    public Builder clearTimeLength() {
      
      timeLength_ = 0D;
      onChanged();
      return this;
    }

    private long startTime_ ;
    /**
     * <code>uint64 startTime = 8;</code>
     */
    public long getStartTime() {
      return startTime_;
    }
    /**
     * <code>uint64 startTime = 8;</code>
     */
    public Builder setStartTime(long value) {
      
      startTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 startTime = 8;</code>
     */
    public Builder clearStartTime() {
      
      startTime_ = 0L;
      onChanged();
      return this;
    }

    private long endTime_ ;
    /**
     * <code>uint64 endTime = 9;</code>
     */
    public long getEndTime() {
      return endTime_;
    }
    /**
     * <code>uint64 endTime = 9;</code>
     */
    public Builder setEndTime(long value) {
      
      endTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 endTime = 9;</code>
     */
    public Builder clearEndTime() {
      
      endTime_ = 0L;
      onChanged();
      return this;
    }

    private int status_ ;
    /**
     * <code>uint32 status = 10;</code>
     */
    public int getStatus() {
      return status_;
    }
    /**
     * <code>uint32 status = 10;</code>
     */
    public Builder setStatus(int value) {
      
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 status = 10;</code>
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }

    private Object interfaceType_ = "";
    /**
     * <code>string interfaceType = 11;</code>
     */
    public String getInterfaceType() {
      Object ref = interfaceType_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        interfaceType_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string interfaceType = 11;</code>
     */
    public com.google.protobuf.ByteString
        getInterfaceTypeBytes() {
      Object ref = interfaceType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        interfaceType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string interfaceType = 11;</code>
     */
    public Builder setInterfaceType(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      interfaceType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string interfaceType = 11;</code>
     */
    public Builder clearInterfaceType() {
      
      interfaceType_ = getDefaultInstance().getInterfaceType();
      onChanged();
      return this;
    }
    /**
     * <code>string interfaceType = 11;</code>
     */
    public Builder setInterfaceTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      interfaceType_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:nftask.NfTaskReq)
  }

  // @@protoc_insertion_point(class_scope:nftask.NfTaskReq)
  private static final NfTaskReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new NfTaskReq();
  }

  public static NfTaskReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NfTaskReq>
      PARSER = new com.google.protobuf.AbstractParser<NfTaskReq>() {
    public NfTaskReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new NfTaskReq(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<NfTaskReq> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<NfTaskReq> getParserForType() {
    return PARSER;
  }

  public NfTaskReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

