// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: alarm.proto

package org.xgvela.oam.alarm;

public interface AlarmRspOrBuilder extends
    // @@protoc_insertion_point(interface_extends:alarm.AlarmRsp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *0 succ, other fail
   * </pre>
   *
   * <code>string result = 1;</code>
   */
  String getResult();
  /**
   * <pre>
   *0 succ, other fail
   * </pre>
   *
   * <code>string result = 1;</code>
   */
  com.google.protobuf.ByteString
      getResultBytes();
}
