// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: traceinfo.proto

package org.xgvela.oam.traceinfo;

public interface TraceInfoReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:traceinfo.TraceInfoReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string taskId = 1;</code>
   */
  String getTaskId();
  /**
   * <code>string taskId = 1;</code>
   */
  com.google.protobuf.ByteString
      getTaskIdBytes();

  /**
   * <code>bytes data = 2;</code>
   */
  com.google.protobuf.ByteString getData();
}
