// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: traceinfo.proto

package org.xgvela.oam.traceinfo;

public final class TraceInfo {
  private TraceInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_traceinfo_TraceInfoReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_traceinfo_TraceInfoReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_traceinfo_TraceInfoResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_traceinfo_TraceInfoResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017traceinfo.proto\022\ttraceinfo\",\n\014TraceInf" +
      "oReq\022\016\n\006taskId\030\001 \001(\t\022\014\n\004data\030\002 \001(\014\"\037\n\rTr" +
      "aceInfoResp\022\016\n\006result\030\001 \001(\t2Z\n\020TraceInfo" +
      "Service\022F\n\017InformTraceInfo\022\027.traceinfo.T" +
      "raceInfoReq\032\030.traceinfo.TraceInfoResp\"\000B" +
      ",\n\030org.xgvela.oam.traceinfoB\tTraceInfoP\001" +
      "\242\002\002TIb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_traceinfo_TraceInfoReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_traceinfo_TraceInfoReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_traceinfo_TraceInfoReq_descriptor,
        new String[] { "TaskId", "Data", });
    internal_static_traceinfo_TraceInfoResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_traceinfo_TraceInfoResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_traceinfo_TraceInfoResp_descriptor,
        new String[] { "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
