// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: traceinfo.proto

package org.xgvela.oam.traceinfo;

public interface TraceInfoRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:traceinfo.TraceInfoResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string result = 1;</code>
   */
  String getResult();
  /**
   * <code>string result = 1;</code>
   */
  com.google.protobuf.ByteString
      getResultBytes();
}
