// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: configuremanagerwithfile.proto

package org.xgvela.oam.configuremanagerwithfile;

public final class ConfigureManagerWithFile {
  private ConfigureManagerWithFile() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_configuremanagerwithfile_UpdateCfgFileWithFileReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_configuremanagerwithfile_UpdateCfgFileWithFileReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_configuremanagerwithfile_UpdateCfgWithFileRsp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_configuremanagerwithfile_UpdateCfgWithFileRsp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\036configuremanagerwithfile.proto\022\030config" +
      "uremanagerwithfile\"l\n\030UpdateCfgFileWithF" +
      "ileReq\022\016\n\006nfType\030\001 \001(\t\022\014\n\004neId\030\002 \001(\t\022\016\n\006" +
      "taskId\030\003 \001(\t\022\020\n\010fileName\030\004 \001(\t\022\020\n\010fileDa" +
      "ta\030\005 \001(\014\")\n\024UpdateCfgWithFileRsp\022\021\n\tupda" +
      "teRsp\030\001 \001(\t2\241\001\n\037ConfigureManagerWithFile" +
      "Service\022~\n\024UpdateConfigWithFile\0222.config" +
      "uremanagerwithfile.UpdateCfgFileWithFile" +
      "Req\032..configuremanagerwithfile.UpdateCfg" +
      "WithFileRsp\"\000(\001BL\n\'org.xgvela.oam.config",
      "uremanagerwithfileB\030ConfigureManagerWith" +
      "FileP\001\242\002\004CMWFb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_configuremanagerwithfile_UpdateCfgFileWithFileReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_configuremanagerwithfile_UpdateCfgFileWithFileReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_configuremanagerwithfile_UpdateCfgFileWithFileReq_descriptor,
        new String[] { "NfType", "NeId", "TaskId", "FileName", "FileData", });
    internal_static_configuremanagerwithfile_UpdateCfgWithFileRsp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_configuremanagerwithfile_UpdateCfgWithFileRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_configuremanagerwithfile_UpdateCfgWithFileRsp_descriptor,
        new String[] { "UpdateRsp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
