// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tubevnf.proto

package org.xgvela.oam.tubevnf;

public final class TubeVnf {
  private TubeVnf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tubevnf_VnfReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tubevnf_VnfReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tubevnf_VnfResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tubevnf_VnfResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rtubevnf.proto\022\007tubevnf\"8\n\006VnfReq\022\016\n\006ne" +
      "Type\030\001 \001(\t\022\014\n\004neId\030\002 \001(\t\022\020\n\010systemId\030\003 \001" +
      "(\t\"\031\n\007VnfResp\022\016\n\006result\030\001 \001(\t2r\n\016TubeVnf" +
      "Service\022.\n\007TubeVnf\022\017.tubevnf.VnfReq\032\020.tu" +
      "bevnf.VnfResp\"\000\0220\n\tDeTubeVnf\022\017.tubevnf.V" +
      "nfReq\032\020.tubevnf.VnfResp\"\000B-\n\026org.xgvela." +
      "oam.tubevnfB\007TubeVnfP\001\242\002\007tubevnfb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_tubevnf_VnfReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tubevnf_VnfReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tubevnf_VnfReq_descriptor,
        new String[] { "NeType", "NeId", "SystemId", });
    internal_static_tubevnf_VnfResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tubevnf_VnfResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tubevnf_VnfResp_descriptor,
        new String[] { "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
