// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tubevnf.proto

package org.xgvela.oam.tubevnf;

public interface VnfReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tubevnf.VnfReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string neType = 1;</code>
   */
  String getNeType();
  /**
   * <code>string neType = 1;</code>
   */
  com.google.protobuf.ByteString
      getNeTypeBytes();

  /**
   * <code>string neId = 2;</code>
   */
  String getNeId();
  /**
   * <code>string neId = 2;</code>
   */
  com.google.protobuf.ByteString
      getNeIdBytes();

  /**
   * <code>string systemId = 3;</code>
   */
  String getSystemId();
  /**
   * <code>string systemId = 3;</code>
   */
  com.google.protobuf.ByteString
      getSystemIdBytes();
}
