// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tubevnf.proto

package org.xgvela.oam.tubevnf;

public interface VnfRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tubevnf.VnfResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string result = 1;</code>
   */
  String getResult();
  /**
   * <code>string result = 1;</code>
   */
  com.google.protobuf.ByteString
      getResultBytes();
}
