management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  cloud:
    nacos:
      discovery:
        enabled: true
        namespace: 75975ef0-c6c1-44ee-a541-ee4334ad7a59
        server-addr: 111.111.63.136:30430
