// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: heartbeat.proto

package org.xgvela.oam.heartbeat;

public interface HeartReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:heartbeat.HeartReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string neType = 1;</code>
   */
  String getNeType();
  /**
   * <code>string neType = 1;</code>
   */
  com.google.protobuf.ByteString
      getNeTypeBytes();

  /**
   * <code>string neId = 2;</code>
   */
  String getNeId();
  /**
   * <code>string neId = 2;</code>
   */
  com.google.protobuf.ByteString
      getNeIdBytes();
}
