// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: heartbeat.proto

package org.xgvela.oam.heartbeat;

public interface HeartRspOrBuilder extends
    // @@protoc_insertion_point(interface_extends:heartbeat.HeartRsp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string result = 1;</code>
   */
  String getResult();
  /**
   * <code>string result = 1;</code>
   */
  com.google.protobuf.ByteString
      getResultBytes();
}
