// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: heartbeat.proto

package org.xgvela.oam.heartbeat;

public final class HeartBeat {
  private HeartBeat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_heartbeat_HeartReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_heartbeat_HeartReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_heartbeat_HeartRsp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_heartbeat_HeartRsp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017heartbeat.proto\022\theartbeat\"(\n\010HeartReq" +
      "\022\016\n\006neType\030\001 \001(\t\022\014\n\004neId\030\002 \001(\t\"\032\n\010HeartR" +
      "sp\022\016\n\006result\030\001 \001(\t2W\n\026HeartBeatReportSer" +
      "vice\022=\n\017HeartBeatReport\022\023.heartbeat.Hear" +
      "tReq\032\023.heartbeat.HeartRsp\"\000B,\n\030com.inspu" +
      "r.oam.heartbeatB\tHeartBeatP\001\242\002\002HBb\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_heartbeat_HeartReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_heartbeat_HeartReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_heartbeat_HeartReq_descriptor,
        new String[] { "NeType", "NeId", });
    internal_static_heartbeat_HeartRsp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_heartbeat_HeartRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_heartbeat_HeartRsp_descriptor,
        new String[] { "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
