// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resource.proto

package org.xgvela.oam.resource;

public interface GetFileRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:resource.GetFileResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *0succ,otherfail
   * </pre>
   *
   * <code>string result = 1;</code>
   */
  String getResult();
  /**
   * <pre>
   *0succ,otherfail
   * </pre>
   *
   * <code>string result = 1;</code>
   */
  com.google.protobuf.ByteString
      getResultBytes();

  /**
   * <pre>
   *filecontents,ifsuccess
   * </pre>
   *
   * <code>bytes fileData = 2;</code>
   */
  com.google.protobuf.ByteString getFileData();
}
