// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resource.proto

package org.xgvela.oam.resource;

public final class resource {
  private resource() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_resource_GetFileResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_resource_GetFileResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_resource_GetFileReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_resource_GetFileReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016resource.proto\022\010resource\"/\n\013GetFileRes" +
      "p\022\016\n\006result\030\001 \001(\t\022\020\n\010fileData\030\002 \001(\014\"<\n\nG" +
      "etFileReq\022\016\n\006nfType\030\001 \001(\t\022\014\n\004neId\030\002 \001(\t\022" +
      "\020\n\010fileName\030\003 \001(\t2O\n\016SyncResService\022=\n\nG" +
      "etResFile\022\024.resource.GetFileReq\032\025.resour" +
      "ce.GetFileResp\"\0000\001B0\n\027org.xgvela.oam.res" +
      "ourceB\010resourceP\001\242\002\010resourceb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_resource_GetFileResp_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_resource_GetFileResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_resource_GetFileResp_descriptor,
        new String[] { "Result", "FileData", });
    internal_static_resource_GetFileReq_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_resource_GetFileReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_resource_GetFileReq_descriptor,
        new String[] { "NfType", "NeId", "FileName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
