// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: configcmd.proto

package org.xgvela.oam.configcmd;

public interface UpdateCfgReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:configcmd.UpdateCfgReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string NfType = 1;</code>
   */
  String getNfType();
  /**
   * <code>string NfType = 1;</code>
   */
  com.google.protobuf.ByteString
      getNfTypeBytes();

  /**
   * <code>string InstanceId = 2;</code>
   */
  String getInstanceId();
  /**
   * <code>string InstanceId = 2;</code>
   */
  com.google.protobuf.ByteString
      getInstanceIdBytes();

  /**
   * <code>uint32 UpdateType = 3;</code>
   */
  int getUpdateType();

  /**
   * <code>uint32 MsgId = 4;</code>
   */
  int getMsgId();

  /**
   * <code>string FileName = 5;</code>
   */
  String getFileName();
  /**
   * <code>string FileName = 5;</code>
   */
  com.google.protobuf.ByteString
      getFileNameBytes();

  /**
   * <pre>
   *filecontents
   * </pre>
   *
   * <code>bytes FileData = 6;</code>
   */
  com.google.protobuf.ByteString getFileData();
}
