// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: configcmd.proto

package org.xgvela.oam.configcmd;

public interface UpdateCfgRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:configcmd.UpdateCfgResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *0succ1failed2needreboot
   * </pre>
   *
   * <code>string UpdateRsp = 1;</code>
   */
  String getUpdateRsp();
  /**
   * <pre>
   *0succ1failed2needreboot
   * </pre>
   *
   * <code>string UpdateRsp = 1;</code>
   */
  com.google.protobuf.ByteString
      getUpdateRspBytes();
}
