// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: syncconfig.proto

package org.xgvela.oam.syncconfig;

public interface GetFileRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:syncconfig.GetFileResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *0 succ, other fail
   * </pre>
   *
   * <code>string result = 1;</code>
   */
  java.lang.String getResult();
  /**
   * <pre>
   *0 succ, other fail
   * </pre>
   *
   * <code>string result = 1;</code>
   */
  com.google.protobuf.ByteString
      getResultBytes();

  /**
   * <pre>
   *file contents,if success
   * </pre>
   *
   * <code>bytes fileData = 2;</code>
   */
  com.google.protobuf.ByteString getFileData();
}
