// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: syncconfig.proto

package org.xgvela.oam.syncconfig;

public interface GetFileReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:syncconfig.GetFileReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string nfType = 1;</code>
   */
  String getNfType();
  /**
   * <code>string nfType = 1;</code>
   */
  com.google.protobuf.ByteString
      getNfTypeBytes();

  /**
   * <code>string neId = 2;</code>
   */
  String getNeId();
  /**
   * <code>string neId = 2;</code>
   */
  com.google.protobuf.ByteString
      getNeIdBytes();

  /**
   * <code>string fileName = 3;</code>
   */
  String getFileName();
  /**
   * <code>string fileName = 3;</code>
   */
  com.google.protobuf.ByteString
      getFileNameBytes();
}
