// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: configuremanager.proto

package org.xgvela.oam.configuremanager;

/**
 * Protobuf type {@code configuremanager.UpdateCfgFileRsp}
 */
public  final class UpdateCfgFileRsp extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:configuremanager.UpdateCfgFileRsp)
    UpdateCfgFileRspOrBuilder {
  // Use UpdateCfgFileRsp.newBuilder() to construct.
  private UpdateCfgFileRsp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UpdateCfgFileRsp() {
    updateRsp_ = "";
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private UpdateCfgFileRsp(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            String s = input.readStringRequireUtf8();

            updateRsp_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ConfigureManager.internal_static_configuremanager_UpdateCfgFileRsp_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ConfigureManager.internal_static_configuremanager_UpdateCfgFileRsp_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            UpdateCfgFileRsp.class, Builder.class);
  }

  public static final int UPDATERSP_FIELD_NUMBER = 1;
  private volatile Object updateRsp_;
  /**
   * <pre>
   * 0 succ 1 failed 2 need reboot
   * </pre>
   *
   * <code>string updateRsp = 1;</code>
   */
  public String getUpdateRsp() {
    Object ref = updateRsp_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      updateRsp_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 0 succ 1 failed 2 need reboot
   * </pre>
   *
   * <code>string updateRsp = 1;</code>
   */
  public com.google.protobuf.ByteString
      getUpdateRspBytes() {
    Object ref = updateRsp_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      updateRsp_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getUpdateRspBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, updateRsp_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getUpdateRspBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, updateRsp_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof UpdateCfgFileRsp)) {
      return super.equals(obj);
    }
    UpdateCfgFileRsp other = (UpdateCfgFileRsp) obj;

    boolean result = true;
    result = result && getUpdateRsp()
        .equals(other.getUpdateRsp());
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + UPDATERSP_FIELD_NUMBER;
    hash = (53 * hash) + getUpdateRsp().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static UpdateCfgFileRsp parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static UpdateCfgFileRsp parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static UpdateCfgFileRsp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static UpdateCfgFileRsp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static UpdateCfgFileRsp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static UpdateCfgFileRsp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static UpdateCfgFileRsp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static UpdateCfgFileRsp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static UpdateCfgFileRsp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static UpdateCfgFileRsp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static UpdateCfgFileRsp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static UpdateCfgFileRsp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(UpdateCfgFileRsp prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code configuremanager.UpdateCfgFileRsp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:configuremanager.UpdateCfgFileRsp)
      UpdateCfgFileRspOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ConfigureManager.internal_static_configuremanager_UpdateCfgFileRsp_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ConfigureManager.internal_static_configuremanager_UpdateCfgFileRsp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              UpdateCfgFileRsp.class, Builder.class);
    }

    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      updateRsp_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ConfigureManager.internal_static_configuremanager_UpdateCfgFileRsp_descriptor;
    }

    public UpdateCfgFileRsp getDefaultInstanceForType() {
      return UpdateCfgFileRsp.getDefaultInstance();
    }

    public UpdateCfgFileRsp build() {
      UpdateCfgFileRsp result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public UpdateCfgFileRsp buildPartial() {
      UpdateCfgFileRsp result = new UpdateCfgFileRsp(this);
      result.updateRsp_ = updateRsp_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof UpdateCfgFileRsp) {
        return mergeFrom((UpdateCfgFileRsp)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(UpdateCfgFileRsp other) {
      if (other == UpdateCfgFileRsp.getDefaultInstance()) return this;
      if (!other.getUpdateRsp().isEmpty()) {
        updateRsp_ = other.updateRsp_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      UpdateCfgFileRsp parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (UpdateCfgFileRsp) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object updateRsp_ = "";
    /**
     * <pre>
     * 0 succ 1 failed 2 need reboot
     * </pre>
     *
     * <code>string updateRsp = 1;</code>
     */
    public String getUpdateRsp() {
      Object ref = updateRsp_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        updateRsp_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * 0 succ 1 failed 2 need reboot
     * </pre>
     *
     * <code>string updateRsp = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUpdateRspBytes() {
      Object ref = updateRsp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        updateRsp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 0 succ 1 failed 2 need reboot
     * </pre>
     *
     * <code>string updateRsp = 1;</code>
     */
    public Builder setUpdateRsp(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      updateRsp_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 0 succ 1 failed 2 need reboot
     * </pre>
     *
     * <code>string updateRsp = 1;</code>
     */
    public Builder clearUpdateRsp() {
      
      updateRsp_ = getDefaultInstance().getUpdateRsp();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 0 succ 1 failed 2 need reboot
     * </pre>
     *
     * <code>string updateRsp = 1;</code>
     */
    public Builder setUpdateRspBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      updateRsp_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:configuremanager.UpdateCfgFileRsp)
  }

  // @@protoc_insertion_point(class_scope:configuremanager.UpdateCfgFileRsp)
  private static final UpdateCfgFileRsp DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new UpdateCfgFileRsp();
  }

  public static UpdateCfgFileRsp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UpdateCfgFileRsp>
      PARSER = new com.google.protobuf.AbstractParser<UpdateCfgFileRsp>() {
    public UpdateCfgFileRsp parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new UpdateCfgFileRsp(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UpdateCfgFileRsp> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<UpdateCfgFileRsp> getParserForType() {
    return PARSER;
  }

  public UpdateCfgFileRsp getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

