// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: configuremanager.proto

package org.xgvela.oam.configuremanager;

public interface UpdateCfgFileReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:configuremanager.UpdateCfgFileReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string nfType = 1;</code>
   */
  String getNfType();
  /**
   * <code>string nfType = 1;</code>
   */
  com.google.protobuf.ByteString
      getNfTypeBytes();

  /**
   * <code>string neId = 2;</code>
   */
  String getNeId();
  /**
   * <code>string neId = 2;</code>
   */
  com.google.protobuf.ByteString
      getNeIdBytes();

  /**
   * <code>string taskId = 3;</code>
   */
  String getTaskId();
  /**
   * <code>string taskId = 3;</code>
   */
  com.google.protobuf.ByteString
      getTaskIdBytes();

  /**
   * <code>string fileName = 4;</code>
   */
  String getFileName();
  /**
   * <code>string fileName = 4;</code>
   */
  com.google.protobuf.ByteString
      getFileNameBytes();
}
