// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: configuremanager.proto

package org.xgvela.oam.configuremanager;

public interface UpdateCfgFileRspOrBuilder extends
    // @@protoc_insertion_point(interface_extends:configuremanager.UpdateCfgFileRsp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 0 succ 1 failed 2 need reboot
   * </pre>
   *
   * <code>string updateRsp = 1;</code>
   */
  String getUpdateRsp();
  /**
   * <pre>
   * 0 succ 1 failed 2 need reboot
   * </pre>
   *
   * <code>string updateRsp = 1;</code>
   */
  com.google.protobuf.ByteString
      getUpdateRspBytes();
}
