// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: configuremanager.proto

package org.xgvela.oam.configuremanager;

/**
 * Protobuf type {@code configuremanager.UpdateCfgFileRsps}
 */
public  final class UpdateCfgFileRsps extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:configuremanager.UpdateCfgFileRsps)
    UpdateCfgFileRspsOrBuilder {
  // Use UpdateCfgFileRsps.newBuilder() to construct.
  private UpdateCfgFileRsps(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UpdateCfgFileRsps() {
    updateRsp_ = java.util.Collections.emptyList();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private UpdateCfgFileRsps(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              updateRsp_ = new java.util.ArrayList<UpdateCfgFileRsp>();
              mutable_bitField0_ |= 0x00000001;
            }
            updateRsp_.add(
                input.readMessage(UpdateCfgFileRsp.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        updateRsp_ = java.util.Collections.unmodifiableList(updateRsp_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ConfigureManager.internal_static_configuremanager_UpdateCfgFileRsps_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ConfigureManager.internal_static_configuremanager_UpdateCfgFileRsps_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            UpdateCfgFileRsps.class, Builder.class);
  }

  public static final int UPDATERSP_FIELD_NUMBER = 1;
  private java.util.List<UpdateCfgFileRsp> updateRsp_;
  /**
   * <pre>
   * 0 succ 1 failed 2 need reboot
   * </pre>
   *
   * <code>repeated .configuremanager.UpdateCfgFileRsp updateRsp = 1;</code>
   */
  public java.util.List<UpdateCfgFileRsp> getUpdateRspList() {
    return updateRsp_;
  }
  /**
   * <pre>
   * 0 succ 1 failed 2 need reboot
   * </pre>
   *
   * <code>repeated .configuremanager.UpdateCfgFileRsp updateRsp = 1;</code>
   */
  public java.util.List<? extends UpdateCfgFileRspOrBuilder>
      getUpdateRspOrBuilderList() {
    return updateRsp_;
  }
  /**
   * <pre>
   * 0 succ 1 failed 2 need reboot
   * </pre>
   *
   * <code>repeated .configuremanager.UpdateCfgFileRsp updateRsp = 1;</code>
   */
  public int getUpdateRspCount() {
    return updateRsp_.size();
  }
  /**
   * <pre>
   * 0 succ 1 failed 2 need reboot
   * </pre>
   *
   * <code>repeated .configuremanager.UpdateCfgFileRsp updateRsp = 1;</code>
   */
  public UpdateCfgFileRsp getUpdateRsp(int index) {
    return updateRsp_.get(index);
  }
  /**
   * <pre>
   * 0 succ 1 failed 2 need reboot
   * </pre>
   *
   * <code>repeated .configuremanager.UpdateCfgFileRsp updateRsp = 1;</code>
   */
  public UpdateCfgFileRspOrBuilder getUpdateRspOrBuilder(
      int index) {
    return updateRsp_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < updateRsp_.size(); i++) {
      output.writeMessage(1, updateRsp_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < updateRsp_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, updateRsp_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof UpdateCfgFileRsps)) {
      return super.equals(obj);
    }
    UpdateCfgFileRsps other = (UpdateCfgFileRsps) obj;

    boolean result = true;
    result = result && getUpdateRspList()
        .equals(other.getUpdateRspList());
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getUpdateRspCount() > 0) {
      hash = (37 * hash) + UPDATERSP_FIELD_NUMBER;
      hash = (53 * hash) + getUpdateRspList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static UpdateCfgFileRsps parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static UpdateCfgFileRsps parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static UpdateCfgFileRsps parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static UpdateCfgFileRsps parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static UpdateCfgFileRsps parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static UpdateCfgFileRsps parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static UpdateCfgFileRsps parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static UpdateCfgFileRsps parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static UpdateCfgFileRsps parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static UpdateCfgFileRsps parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static UpdateCfgFileRsps parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static UpdateCfgFileRsps parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(UpdateCfgFileRsps prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code configuremanager.UpdateCfgFileRsps}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:configuremanager.UpdateCfgFileRsps)
      UpdateCfgFileRspsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ConfigureManager.internal_static_configuremanager_UpdateCfgFileRsps_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ConfigureManager.internal_static_configuremanager_UpdateCfgFileRsps_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              UpdateCfgFileRsps.class, Builder.class);
    }

    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getUpdateRspFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (updateRspBuilder_ == null) {
        updateRsp_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        updateRspBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ConfigureManager.internal_static_configuremanager_UpdateCfgFileRsps_descriptor;
    }

    public UpdateCfgFileRsps getDefaultInstanceForType() {
      return UpdateCfgFileRsps.getDefaultInstance();
    }

    public UpdateCfgFileRsps build() {
      UpdateCfgFileRsps result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public UpdateCfgFileRsps buildPartial() {
      UpdateCfgFileRsps result = new UpdateCfgFileRsps(this);
      int from_bitField0_ = bitField0_;
      if (updateRspBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          updateRsp_ = java.util.Collections.unmodifiableList(updateRsp_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.updateRsp_ = updateRsp_;
      } else {
        result.updateRsp_ = updateRspBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof UpdateCfgFileRsps) {
        return mergeFrom((UpdateCfgFileRsps)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(UpdateCfgFileRsps other) {
      if (other == UpdateCfgFileRsps.getDefaultInstance()) return this;
      if (updateRspBuilder_ == null) {
        if (!other.updateRsp_.isEmpty()) {
          if (updateRsp_.isEmpty()) {
            updateRsp_ = other.updateRsp_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureUpdateRspIsMutable();
            updateRsp_.addAll(other.updateRsp_);
          }
          onChanged();
        }
      } else {
        if (!other.updateRsp_.isEmpty()) {
          if (updateRspBuilder_.isEmpty()) {
            updateRspBuilder_.dispose();
            updateRspBuilder_ = null;
            updateRsp_ = other.updateRsp_;
            bitField0_ = (bitField0_ & ~0x00000001);
            updateRspBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getUpdateRspFieldBuilder() : null;
          } else {
            updateRspBuilder_.addAllMessages(other.updateRsp_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      UpdateCfgFileRsps parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (UpdateCfgFileRsps) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<UpdateCfgFileRsp> updateRsp_ =
      java.util.Collections.emptyList();
    private void ensureUpdateRspIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        updateRsp_ = new java.util.ArrayList<UpdateCfgFileRsp>(updateRsp_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        UpdateCfgFileRsp, UpdateCfgFileRsp.Builder, UpdateCfgFileRspOrBuilder> updateRspBuilder_;

    /**
     * <pre>
     * 0 succ 1 failed 2 need reboot
     * </pre>
     *
     * <code>repeated .configuremanager.UpdateCfgFileRsp updateRsp = 1;</code>
     */
    public java.util.List<UpdateCfgFileRsp> getUpdateRspList() {
      if (updateRspBuilder_ == null) {
        return java.util.Collections.unmodifiableList(updateRsp_);
      } else {
        return updateRspBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * 0 succ 1 failed 2 need reboot
     * </pre>
     *
     * <code>repeated .configuremanager.UpdateCfgFileRsp updateRsp = 1;</code>
     */
    public int getUpdateRspCount() {
      if (updateRspBuilder_ == null) {
        return updateRsp_.size();
      } else {
        return updateRspBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * 0 succ 1 failed 2 need reboot
     * </pre>
     *
     * <code>repeated .configuremanager.UpdateCfgFileRsp updateRsp = 1;</code>
     */
    public UpdateCfgFileRsp getUpdateRsp(int index) {
      if (updateRspBuilder_ == null) {
        return updateRsp_.get(index);
      } else {
        return updateRspBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * 0 succ 1 failed 2 need reboot
     * </pre>
     *
     * <code>repeated .configuremanager.UpdateCfgFileRsp updateRsp = 1;</code>
     */
    public Builder setUpdateRsp(
        int index, UpdateCfgFileRsp value) {
      if (updateRspBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUpdateRspIsMutable();
        updateRsp_.set(index, value);
        onChanged();
      } else {
        updateRspBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 0 succ 1 failed 2 need reboot
     * </pre>
     *
     * <code>repeated .configuremanager.UpdateCfgFileRsp updateRsp = 1;</code>
     */
    public Builder setUpdateRsp(
        int index, UpdateCfgFileRsp.Builder builderForValue) {
      if (updateRspBuilder_ == null) {
        ensureUpdateRspIsMutable();
        updateRsp_.set(index, builderForValue.build());
        onChanged();
      } else {
        updateRspBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 0 succ 1 failed 2 need reboot
     * </pre>
     *
     * <code>repeated .configuremanager.UpdateCfgFileRsp updateRsp = 1;</code>
     */
    public Builder addUpdateRsp(UpdateCfgFileRsp value) {
      if (updateRspBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUpdateRspIsMutable();
        updateRsp_.add(value);
        onChanged();
      } else {
        updateRspBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * 0 succ 1 failed 2 need reboot
     * </pre>
     *
     * <code>repeated .configuremanager.UpdateCfgFileRsp updateRsp = 1;</code>
     */
    public Builder addUpdateRsp(
        int index, UpdateCfgFileRsp value) {
      if (updateRspBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureUpdateRspIsMutable();
        updateRsp_.add(index, value);
        onChanged();
      } else {
        updateRspBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * 0 succ 1 failed 2 need reboot
     * </pre>
     *
     * <code>repeated .configuremanager.UpdateCfgFileRsp updateRsp = 1;</code>
     */
    public Builder addUpdateRsp(
        UpdateCfgFileRsp.Builder builderForValue) {
      if (updateRspBuilder_ == null) {
        ensureUpdateRspIsMutable();
        updateRsp_.add(builderForValue.build());
        onChanged();
      } else {
        updateRspBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 0 succ 1 failed 2 need reboot
     * </pre>
     *
     * <code>repeated .configuremanager.UpdateCfgFileRsp updateRsp = 1;</code>
     */
    public Builder addUpdateRsp(
        int index, UpdateCfgFileRsp.Builder builderForValue) {
      if (updateRspBuilder_ == null) {
        ensureUpdateRspIsMutable();
        updateRsp_.add(index, builderForValue.build());
        onChanged();
      } else {
        updateRspBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * 0 succ 1 failed 2 need reboot
     * </pre>
     *
     * <code>repeated .configuremanager.UpdateCfgFileRsp updateRsp = 1;</code>
     */
    public Builder addAllUpdateRsp(
        Iterable<? extends UpdateCfgFileRsp> values) {
      if (updateRspBuilder_ == null) {
        ensureUpdateRspIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, updateRsp_);
        onChanged();
      } else {
        updateRspBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * 0 succ 1 failed 2 need reboot
     * </pre>
     *
     * <code>repeated .configuremanager.UpdateCfgFileRsp updateRsp = 1;</code>
     */
    public Builder clearUpdateRsp() {
      if (updateRspBuilder_ == null) {
        updateRsp_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        updateRspBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 0 succ 1 failed 2 need reboot
     * </pre>
     *
     * <code>repeated .configuremanager.UpdateCfgFileRsp updateRsp = 1;</code>
     */
    public Builder removeUpdateRsp(int index) {
      if (updateRspBuilder_ == null) {
        ensureUpdateRspIsMutable();
        updateRsp_.remove(index);
        onChanged();
      } else {
        updateRspBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * 0 succ 1 failed 2 need reboot
     * </pre>
     *
     * <code>repeated .configuremanager.UpdateCfgFileRsp updateRsp = 1;</code>
     */
    public UpdateCfgFileRsp.Builder getUpdateRspBuilder(
        int index) {
      return getUpdateRspFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * 0 succ 1 failed 2 need reboot
     * </pre>
     *
     * <code>repeated .configuremanager.UpdateCfgFileRsp updateRsp = 1;</code>
     */
    public UpdateCfgFileRspOrBuilder getUpdateRspOrBuilder(
        int index) {
      if (updateRspBuilder_ == null) {
        return updateRsp_.get(index);  } else {
        return updateRspBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * 0 succ 1 failed 2 need reboot
     * </pre>
     *
     * <code>repeated .configuremanager.UpdateCfgFileRsp updateRsp = 1;</code>
     */
    public java.util.List<? extends UpdateCfgFileRspOrBuilder>
         getUpdateRspOrBuilderList() {
      if (updateRspBuilder_ != null) {
        return updateRspBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(updateRsp_);
      }
    }
    /**
     * <pre>
     * 0 succ 1 failed 2 need reboot
     * </pre>
     *
     * <code>repeated .configuremanager.UpdateCfgFileRsp updateRsp = 1;</code>
     */
    public UpdateCfgFileRsp.Builder addUpdateRspBuilder() {
      return getUpdateRspFieldBuilder().addBuilder(
          UpdateCfgFileRsp.getDefaultInstance());
    }
    /**
     * <pre>
     * 0 succ 1 failed 2 need reboot
     * </pre>
     *
     * <code>repeated .configuremanager.UpdateCfgFileRsp updateRsp = 1;</code>
     */
    public UpdateCfgFileRsp.Builder addUpdateRspBuilder(
        int index) {
      return getUpdateRspFieldBuilder().addBuilder(
          index, UpdateCfgFileRsp.getDefaultInstance());
    }
    /**
     * <pre>
     * 0 succ 1 failed 2 need reboot
     * </pre>
     *
     * <code>repeated .configuremanager.UpdateCfgFileRsp updateRsp = 1;</code>
     */
    public java.util.List<UpdateCfgFileRsp.Builder>
         getUpdateRspBuilderList() {
      return getUpdateRspFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        UpdateCfgFileRsp, UpdateCfgFileRsp.Builder, UpdateCfgFileRspOrBuilder>
        getUpdateRspFieldBuilder() {
      if (updateRspBuilder_ == null) {
        updateRspBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            UpdateCfgFileRsp, UpdateCfgFileRsp.Builder, UpdateCfgFileRspOrBuilder>(
                updateRsp_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        updateRsp_ = null;
      }
      return updateRspBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:configuremanager.UpdateCfgFileRsps)
  }

  // @@protoc_insertion_point(class_scope:configuremanager.UpdateCfgFileRsps)
  private static final UpdateCfgFileRsps DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new UpdateCfgFileRsps();
  }

  public static UpdateCfgFileRsps getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UpdateCfgFileRsps>
      PARSER = new com.google.protobuf.AbstractParser<UpdateCfgFileRsps>() {
    public UpdateCfgFileRsps parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new UpdateCfgFileRsps(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UpdateCfgFileRsps> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<UpdateCfgFileRsps> getParserForType() {
    return PARSER;
  }

  public UpdateCfgFileRsps getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

