// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nfregister.proto

package org.xgvela.oam.nfregister;

public final class NFRegister {
  private NFRegister() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nfregister_RegisterReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nfregister_RegisterReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_nfregister_RegisterRsp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_nfregister_RegisterRsp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020nfregister.proto\022\nnfregister\"\177\n\013Regist" +
      "erReq\022\014\n\004neId\030\001 \001(\t\022\017\n\007vnfName\030\002 \001(\t\022\016\n\006" +
      "neType\030\003 \001(\t\022\023\n\013vnfManageIp\030\004 \001(\t\022\025\n\rvnf" +
      "ManagePort\030\005 \001(\t\022\025\n\rvnfSignalPort\030\006 \001(\t\"" +
      "\035\n\013RegisterRsp\022\016\n\006result\030\001 \001(\t2U\n\021NfRegi" +
      "sterService\022@\n\nNfRegister\022\027.nfregister.R" +
      "egisterReq\032\027.nfregister.RegisterRsp\"\000B/\n" +
      "\031com.inspur.oam.nfregisterB\nNFRegisterP\001" +
      "\242\002\003NFRb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_nfregister_RegisterReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_nfregister_RegisterReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nfregister_RegisterReq_descriptor,
        new String[] { "NeId", "VnfName", "NeType", "VnfManageIp", "VnfManagePort", "VnfSignalPort", });
    internal_static_nfregister_RegisterRsp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_nfregister_RegisterRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_nfregister_RegisterRsp_descriptor,
        new String[] { "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
