// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nfregister.proto

package org.xgvela.oam.nfregister;

public interface RegisterRspOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nfregister.RegisterRsp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string result = 1;</code>
   */
  String getResult();
  /**
   * <code>string result = 1;</code>
   */
  com.google.protobuf.ByteString
      getResultBytes();
}
