// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nfregister.proto

package org.xgvela.oam.nfregister;

public interface RegisterReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nfregister.RegisterReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string neId = 1;</code>
   */
  String getNeId();
  /**
   * <code>string neId = 1;</code>
   */
  com.google.protobuf.ByteString
      getNeIdBytes();

  /**
   * <code>string vnfName = 2;</code>
   */
  String getVnfName();
  /**
   * <code>string vnfName = 2;</code>
   */
  com.google.protobuf.ByteString
      getVnfNameBytes();

  /**
   * <code>string neType = 3;</code>
   */
  String getNeType();
  /**
   * <code>string neType = 3;</code>
   */
  com.google.protobuf.ByteString
      getNeTypeBytes();

  /**
   * <code>string vnfManageIp = 4;</code>
   */
  String getVnfManageIp();
  /**
   * <code>string vnfManageIp = 4;</code>
   */
  com.google.protobuf.ByteString
      getVnfManageIpBytes();

  /**
   * <code>string vnfManagePort = 5;</code>
   */
  String getVnfManagePort();
  /**
   * <code>string vnfManagePort = 5;</code>
   */
  com.google.protobuf.ByteString
      getVnfManagePortBytes();

  /**
   * <code>string vnfSignalPort = 6;</code>
   */
  String getVnfSignalPort();
  /**
   * <code>string vnfSignalPort = 6;</code>
   */
  com.google.protobuf.ByteString
      getVnfSignalPortBytes();
}
