// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: configrestore.proto

package org.xgvela.oam.configrestore;

public interface NotifyCfgReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:configrestore.NotifyCfgReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string NfType = 1;</code>
   */
  String getNfType();
  /**
   * <code>string NfType = 1;</code>
   */
  com.google.protobuf.ByteString
      getNfTypeBytes();

  /**
   * <code>string InstanceId = 2;</code>
   */
  String getInstanceId();
  /**
   * <code>string InstanceId = 2;</code>
   */
  com.google.protobuf.ByteString
      getInstanceIdBytes();

  /**
   * <code>string ConfigPath = 3;</code>
   */
  String getConfigPath();
  /**
   * <code>string ConfigPath = 3;</code>
   */
  com.google.protobuf.ByteString
      getConfigPathBytes();

  /**
   * <code>repeated string ConfigFileName = 4;</code>
   */
  java.util.List<String>
      getConfigFileNameList();
  /**
   * <code>repeated string ConfigFileName = 4;</code>
   */
  int getConfigFileNameCount();
  /**
   * <code>repeated string ConfigFileName = 4;</code>
   */
  String getConfigFileName(int index);
  /**
   * <code>repeated string ConfigFileName = 4;</code>
   */
  com.google.protobuf.ByteString
      getConfigFileNameBytes(int index);

  /**
   * <code>string XmlPath = 5;</code>
   */
  String getXmlPath();
  /**
   * <code>string XmlPath = 5;</code>
   */
  com.google.protobuf.ByteString
      getXmlPathBytes();

  /**
   * <code>repeated string XmlFileName = 6;</code>
   */
  java.util.List<String>
      getXmlFileNameList();
  /**
   * <code>repeated string XmlFileName = 6;</code>
   */
  int getXmlFileNameCount();
  /**
   * <code>repeated string XmlFileName = 6;</code>
   */
  String getXmlFileName(int index);
  /**
   * <code>repeated string XmlFileName = 6;</code>
   */
  com.google.protobuf.ByteString
      getXmlFileNameBytes(int index);
}
