// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: configrestore.proto

package org.xgvela.oam.configrestore;

public interface NotifyCfgRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:configrestore.NotifyCfgResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Result = 1;</code>
   */
  String getResult();
  /**
   * <code>string Result = 1;</code>
   */
  com.google.protobuf.ByteString
      getResultBytes();
}
