// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: performance.proto

package org.xgvela.oam.performance;

public interface StatsInfoRspOrBuilder extends
    // @@protoc_insertion_point(interface_extends:performance.StatsInfoRsp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *0 succ, other fail
   * </pre>
   *
   * <code>string result = 1;</code>
   */
  String getResult();
  /**
   * <pre>
   *0 succ, other fail
   * </pre>
   *
   * <code>string result = 1;</code>
   */
  com.google.protobuf.ByteString
      getResultBytes();
}
